image: node:lts

pages:
  stage: deploy
  script:
    - mkdir -p public
    - find . -maxdepth 1 -mindepth 1 ! -name 'public' ! -name '.git' ! -name '.gitlab-ci.yml' -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main